import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Order and grouping come from the numbered folders and _category_.json files
// under docs/, so a new page appears in the nav without editing this file.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
