server.port: 3009

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/acr}
    username: ${SPRING_DATASOURCE_USERNAME:fabric}
    password: ${SPRING_DATASOURCE_PASSWORD:fabric}
  flyway:
    enabled: true
